### ISSUE TITLE
search问题

### ISSUE THREAD

**Issue by vveg26** [plasx520/blog-butterfly#2]
分开安装必备插件中，还需要安装一个npm install hexo-generator-search --save

**Comment by plasx520** [comment]
感谢投稿怕冷爱上雪，您的投稿已收到，当晚就会开始审核。分享精神最可贵，如果稿件没有通过也非常感谢您投稿！软件无怕冷爱上雪版权的审核通过也不会发放奖励请勿使用快压流氓软件打包压缩包 发现一律略过
